name: iOS starter workflow

on:
  push:
    branches: [ "ios-build" ]
  pull_request:
    branches: [ "ios-build" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: version
        run: echo "PROD_FLET_VERSION=${{ github.job }}" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip
          pip install .
          flet build ipa
          ls -la build/ipa/
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.job }}
          tag_name: "v${{ github.job }}"
          body: "new release ${{ github.job }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ipa/Runner.xcarchive
          asset_name: prod-flet.ipa
          asset_content_type: application/octet-stream
