name: iOS starter workflow

on:
  push:
    branches: [ "ios-build" ]
  pull_request:
    branches: [ "ios-build" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip
          pip install .
          flet build ipa
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "0.0.1"
          tag_name: "v0.0.1"
          body: "new release"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/ipa/app-release.ipa
          asset_name: app-release.ipa
          asset_content_type: application/octet-stream
